apiVersion: extensions/v1beta1

kind: Deployment

metadata:
  name: appv2-deploy

spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: myapp
        version: v2
    spec:
      containers:
      - name: myappv2-container
        image: stackupiss/northwind-app:v2
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name: DB_HOST
          value: mydb-svc
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: changeit
        ports:
        - name: myapp-port
          containerPort: 3000
        imagePullPolicy: Always
      restartPolicy: Always