---
apiVersion: v1
kind: Namespace


metadata:
  name: nwapp
  labels:
    version: v1

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: nwapp

data:
  db_host: nwdb-svc.nwapp.svc.cluster.local
  db_password: changeit

---
apiVersion: v1
kind: Secret

metadata:
  name: nwapp-secret
  namespace: nwapp

data:
  db_password: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwdb-deploy
  namespace: nwapp
  labels:
    name: nwdb
    version: v1

spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      name: nwdb
      version: v1
  template:
    metadata:
      name: nwdb-pod
      labels:
        name: nwdb
        version: v1
    spec:
      containers:
      - name: nwdb-container
        image: qingzz/northwind:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        ports: 
        - name: mysql
          containerPort: 3306
---
apiVersion: v1
kind: Service

metadata:
  name: nwdb-svc
  namespace: nwapp
  labels:
    name: nwdb-svc
    version: v1

spec:
  type: ClusterIP
  selector:
    name: nwdb
    version: v1
  ports:
  - name: nwdb-svc-port
    port: 3306
    targetPort: mysql

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwsvr-deploy
  namespace: nwapp
  labels:
    name: nwsvr
    version: v1

spec:
  replicas: 3
  minReadySeconds: 60
  selector:
    matchLabels:
      name: nwsvr
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nwsvr-pod
      labels:
        name: nwsvr
        version: v1
    spec:
      containers:
      - name: nwsvr-container
        image: stackupiss/northwind-app:v2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: nwsvr-port
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nwapp-config
              key: db_host
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports: 
        - name: nwsvr-port
          containerPort: 3000

---
apiVersion: v1
kind: Service

metadata:
  name: nwsvr-svc
  namespace: nwapp
  labels:
    name: nwsvr-svc
    version: v1

spec:
  type: LoadBalancer
  selector:
    name: nwsvr
    version: v1
  ports:
  - name: nwsvr-svc-port
    port: 80
    targetPort: nwsvr-port